# Pandas 入门

In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [3]:
obj = Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7 , -5, 3], index =['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [10]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [17]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [19]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [20]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [22]:
%pylab inline
np.exp(obj2)

Populating the interactive namespace from numpy and matplotlib


d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
# 可以将Series看成是一个定长的有序字典，因为它是索引值到数据值的一个映射
# 它可以用在许多需要字典参数的函数中
'b' in obj2

True

In [25]:
'e' in obj2

False

In [26]:
# 也可以通过Python字典来创建Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [31]:
obj3 = Series(sdata)

In [32]:
obj3                   # 可以发现字典的键是排序过的

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [29]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [33]:
obj4 = Series(sdata, index=states)

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [37]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [39]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [40]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [42]:
obj4.name = 'population'

In [43]:
obj4.index.name = 'state'

In [44]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [46]:
# Series的索引可以通过赋值的方式就地修改
obj.index = ['Bob', 'Steve', 'Jeff','Ryan','GG']

In [47]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
GG       6
dtype: int64

### DataFrame

In [49]:
# 既有行索引，也有列索引，可以看做是由Series组成的字典（共用同一个索引）
# 每一列格式相同, 类似Excel表格
data = {'state':['Ohio','Ohio', "ohio", 'Nevada', 'Nevada'], 'year':[2000, 2001, 2002, 2001, 2002], 'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}

In [50]:
frame = DataFrame(data)

In [51]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [52]:
# 如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列：
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [53]:
# 如果传入的列在数据中找不到，就会产生NA值：
frame2 = DataFrame(data, columns = ['year', 'state', 'pop', 'debt'], index=['one','two','three','four','five'])

In [54]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [55]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [56]:
frame2['state']      # 字典方式

one        Ohio
two        Ohio
three      ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [57]:
frame2.year         # 属性方式

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [58]:
frame2.ix['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [59]:
frame2['debt'] = 16.5

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [61]:
frame2['debt'] = np.arange(5.)

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [63]:
# 将列表或数组赋值给某个列时， 其长度必须跟DataFrame的长度相匹配。
# 如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都会被填上缺失值
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [64]:
frame2['debt'] = val

In [65]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [66]:
# 为不存在的列赋值会创建出一个新列
# 关键字del用于删除列
frame2['eastern'] = frame2.state =='Ohio'

In [67]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    ohio  3.6   NaN   False
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [69]:
del frame2['eastern']

In [74]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [75]:
# 嵌套字典传给DataFrame会被解释为： 外层字典的键作为列，内层键作为行索引
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = DataFrame(pop)

In [76]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [78]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [80]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [81]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [82]:
frame2.values

array([[2000L, 'Ohio', 1.5, nan],
       [2001L, 'Ohio', 1.7, -1.2],
       [2002L, 'ohio', 3.6, nan],
       [2001L, 'Nevada', 2.4, -1.5],
       [2002L, 'Nevada', 2.9, -1.7]], dtype=object)